// DATA =============================
// LOAD
export const LOAD_DATA_SUCCESS = "LOAD_DATA_SUCCESS";
export const LOAD_DATA_FAILURE = "LOAD_DATA_FAILURE";

// ADD
export const ADD_DATA = "ADD_DATA";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_FAILURE = "ADD_DATA_FAILURE";

// SEARCH
export const FILTER_DATA = "FILTER_DATA";
export const FILTER_DATA_SUCCESS = "FILTER_DATA_SUCCESS";
export const FILTER_DATA_FAILURE = "FILTER_DATA_FAILURE";

// ITEM DETAIL ====================
// LOAD
export const LOAD_DETAIL = "LOAD_DETAIL";
export const LOAD_DETAIL_SUCCESS = "LOAD_DETAIL_SUCCESS";
export const LOAD_DETAIL_FAILURE = "LOAD_DETAIL_FAILURE";

// LIKE
export const LIKE_ITEM = "LIKE_ITEM";
export const LIKE_ITEM_SUCCESS = "LIKE_ITEM_SUCCESS";
export const LIKE_ITEM_FAILURE = "LIKE_ITEM_FAILURE";

// BUY
export const BUY_ITEM = "BUY_ITEM";
export const BUY_ITEM_SUCCESS = "BUY_ITEM_SUCCESS";
export const BUY_ITEM_FAILURE = "BUY_ITEM_FAILURE";

// ITEM'S TESTIMONIALS ====================
// LOAD
export const LOAD_TESTIMONIALS = "LOAD_TESTIMONIALS";
export const LOAD_TESTIMONIALS_SUCCESS = "LOAD_TESTIMONIALS_SUCCESS";
export const LOAD_TESTIMONIALS_FAILURE = "LOAD_TESTIMONIALS_FAILURE";

// ADD
export const ADD_TESTIMONIALS = "ADD_TESTIMONIALS";
export const ADD_TESTIMONIALS_SUCCESS = "ADD_TESTIMONIALS_SUCCESS";
export const ADD_TESTIMONIALS_FAILURE = "ADD_TESTIMONIALS_FAILURE";